
//Zero is highest interrupt priority and it decreases with increasing value
#define OSEK_INTERRUPT_LEVEL 
#define OSEK_LEAST_INTERRUPT_LEVEL 
/**********************************************/
//sum of activations of all tasks with the same priority
#define PRIORITY_0_Q_SIZE NOT_USED
#define OS_PRIORITY_0_MAX_STACK_SIZE NOT_USED

#define PRIORITY_1_Q_SIZE NOT_USED
#define OS_PRIORITY_1_MAX_STACK_SIZE NOT_USED

#define PRIORITY_2_Q_SIZE NOT_USED
#define OS_PRIORITY_2_MAX_STACK_SIZE NOT_USED

#define PRIORITY_3_Q_SIZE NOT_USED
#define OS_PRIORITY_3_MAX_STACK_SIZE NOT_USED

#define PRIORITY_4_Q_SIZE NOT_USED
#define OS_PRIORITY_4_MAX_STACK_SIZE NOT_USED

#define PRIORITY_5_Q_SIZE NOT_USED
#define OS_PRIORITY_5_MAX_STACK_SIZE NOT_USED

#define PRIORITY_6_Q_SIZE NOT_USED
#define OS_PRIORITY_6_MAX_STACK_SIZE NOT_USED

#define PRIORITY_7_Q_SIZE NOT_USED
#define OS_PRIORITY_7_MAX_STACK_SIZE NOT_USED

#define PRIORITY_8_Q_SIZE NOT_USED
#define OS_PRIORITY_8_MAX_STACK_SIZE NOT_USED

#define PRIORITY_9_Q_SIZE NOT_USED
#define OS_PRIORITY_9_MAX_STACK_SIZE NOT_USED

#define PRIORITY_10_Q_SIZE NOT_USED
#define OS_PRIORITY_10_MAX_STACK_SIZE NOT_USED

#define PRIORITY_11_Q_SIZE NOT_USED
#define OS_PRIORITY_11_MAX_STACK_SIZE NOT_USED

#define PRIORITY_12_Q_SIZE NOT_USED
#define OS_PRIORITY_12_MAX_STACK_SIZE NOT_USED

#define PRIORITY_13_Q_SIZE NOT_USED
#define OS_PRIORITY_13_MAX_STACK_SIZE NOT_USED

#define PRIORITY_14_Q_SIZE NOT_USED
#define OS_PRIORITY_14_MAX_STACK_SIZE NOT_USED

#define PRIORITY_15_Q_SIZE NOT_USED
#define OS_PRIORITY_15_MAX_STACK_SIZE NOT_USED

#define PRIORITY_16_Q_SIZE NOT_USED
#define OS_PRIORITY_16_MAX_STACK_SIZE NOT_USED

#define PRIORITY_17_Q_SIZE NOT_USED
#define OS_PRIORITY_17_MAX_STACK_SIZE NOT_USED

#define PRIORITY_18_Q_SIZE NOT_USED
#define OS_PRIORITY_18_MAX_STACK_SIZE NOT_USED

#define PRIORITY_19_Q_SIZE NOT_USED
#define OS_PRIORITY_19_MAX_STACK_SIZE NOT_USED

#define PRIORITY_20_Q_SIZE NOT_USED
#define OS_PRIORITY_20_MAX_STACK_SIZE NOT_USED

#define PRIORITY_21_Q_SIZE NOT_USED
#define OS_PRIORITY_21_MAX_STACK_SIZE NOT_USED

#define PRIORITY_22_Q_SIZE NOT_USED
#define OS_PRIORITY_22_MAX_STACK_SIZE NOT_USED

#define PRIORITY_23_Q_SIZE NOT_USED
#define OS_PRIORITY_23_MAX_STACK_SIZE NOT_USED

#define PRIORITY_24_Q_SIZE NOT_USED
#define OS_PRIORITY_24_MAX_STACK_SIZE NOT_USED

#define PRIORITY_25_Q_SIZE NOT_USED
#define OS_PRIORITY_25_MAX_STACK_SIZE NOT_USED

#define PRIORITY_26_Q_SIZE NOT_USED
#define OS_PRIORITY_26_MAX_STACK_SIZE NOT_USED

#define PRIORITY_27_Q_SIZE NOT_USED
#define OS_PRIORITY_27_MAX_STACK_SIZE NOT_USED

#define PRIORITY_28_Q_SIZE NOT_USED
#define OS_PRIORITY_28_MAX_STACK_SIZE NOT_USED

#define PRIORITY_29_Q_SIZE NOT_USED
#define OS_PRIORITY_29_MAX_STACK_SIZE NOT_USED

#define PRIORITY_30_Q_SIZE NOT_USED
#define OS_PRIORITY_30_MAX_STACK_SIZE NOT_USED

#define PRIORITY_31_Q_SIZE NOT_USED
#define OS_PRIORITY_31_MAX_STACK_SIZE NOT_USED

#define PRIORITY_32_Q_SIZE NOT_USED
#define OS_PRIORITY_32_MAX_STACK_SIZE NOT_USED
