POSEK_QUEUE_CREATE(0, PRIORITY_0_Q_SIZE, OS_PRIORITY_0_MAX_STACK_SIZE)
#if (PRIORITY_1_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(1, PRIORITY_1_Q_SIZE, OS_PRIORITY_1_MAX_STACK_SIZE)
#endif
#if (PRIORITY_2_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(2, PRIORITY_2_Q_SIZE, OS_PRIORITY_2_MAX_STACK_SIZE)
#endif
#if (PRIORITY_3_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(3, PRIORITY_3_Q_SIZE, OS_PRIORITY_3_MAX_STACK_SIZE)
#endif
#if (PRIORITY_4_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(4, PRIORITY_4_Q_SIZE, OS_PRIORITY_4_MAX_STACK_SIZE)
#endif
#if (PRIORITY_5_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(5, PRIORITY_5_Q_SIZE, OS_PRIORITY_5_MAX_STACK_SIZE)
#endif
#if (PRIORITY_6_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(6, PRIORITY_6_Q_SIZE, OS_PRIORITY_6_MAX_STACK_SIZE)
#endif
#if (PRIORITY_7_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(7, PRIORITY_7_Q_SIZE, OS_PRIORITY_7_MAX_STACK_SIZE)
#endif
#if (PRIORITY_8_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(8, PRIORITY_8_Q_SIZE, OS_PRIORITY_8_MAX_STACK_SIZE)
#endif
#if (PRIORITY_9_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(9, PRIORITY_9_Q_SIZE, OS_PRIORITY_9_MAX_STACK_SIZE)
#endif
#if (PRIORITY_10_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(10, PRIORITY_10_Q_SIZE, OS_PRIORITY_10_MAX_STACK_SIZE)
#endif
#if (PRIORITY_11_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(11, PRIORITY_11_Q_SIZE, OS_PRIORITY_11_MAX_STACK_SIZE)
#endif
#if (PRIORITY_12_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(12, PRIORITY_12_Q_SIZEPRIORITY_13_Q_SIZE, OS_PRIORITY_12_MAX_STACK_SIZE)
#endif
#if (PRIORITY_13_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(13, PRIORITY_13_Q_SIZE, OS_PRIORITY_13_MAX_STACK_SIZE)
#endif
#if (PRIORITY_14_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(14, PRIORITY_14_Q_SIZE, OS_PRIORITY_14_MAX_STACK_SIZE)
#endif
#if (PRIORITY_15_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(15, PRIORITY_15_Q_SIZE, OS_PRIORITY_15_MAX_STACK_SIZE)
#endif
#if (PRIORITY_16_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(16, PRIORITY_16_Q_SIZE, OS_PRIORITY_16_MAX_STACK_SIZE)
#endif
#if (PRIORITY_17_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(17, PRIORITY_17_Q_SIZE, OS_PRIORITY_17_MAX_STACK_SIZE)
#endif
#if (PRIORITY_18_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(18, PRIORITY_18_Q_SIZE, OS_PRIORITY_18_MAX_STACK_SIZE)
#endif
#if (PRIORITY_19_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(19, PRIORITY_19_Q_SIZE, OS_PRIORITY_19_MAX_STACK_SIZE)
#endif
#if (PRIORITY_20_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(20, PRIORITY_20_Q_SIZE, OS_PRIORITY_20_MAX_STACK_SIZE)
#endif
#if (PRIORITY_21_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(21, PRIORITY_21_Q_SIZE, OS_PRIORITY_21_MAX_STACK_SIZE)
#endif
#if (PRIORITY_22_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(22, PRIORITY_22_Q_SIZE, OS_PRIORITY_22_MAX_STACK_SIZE)
#endif
#if (PRIORITY_23_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(23, PRIORITY_23_Q_SIZE, OS_PRIORITY_23_MAX_STACK_SIZE)
#endif
#if (PRIORITY_24_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(24, PRIORITY_24_Q_SIZE, OS_PRIORITY_24_MAX_STACK_SIZE)
#endif
#if (PRIORITY_25_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(25, PRIORITY_25_Q_SIZE, OS_PRIORITY_25_MAX_STACK_SIZE)
#endif
#if (PRIORITY_26_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(26, PRIORITY_26_Q_SIZE, OS_PRIORITY_26_MAX_STACK_SIZE)
#endif
#if (PRIORITY_27_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(27, PRIORITY_27_Q_SIZE, OS_PRIORITY_27_MAX_STACK_SIZE)
#endif
#if (PRIORITY_28_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(28, PRIORITY_28_Q_SIZE, OS_PRIORITY_28_MAX_STACK_SIZE)
#endif
#if (PRIORITY_29_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(29, PRIORITY_29_Q_SIZE, OS_PRIORITY_29_MAX_STACK_SIZE)
#endif
#if (PRIORITY_30_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(30, PRIORITY_30_Q_SIZE, OS_PRIORITY_30_MAX_STACK_SIZE)
#endif
#if (PRIORITY_31_Q_SIZE != NOT_USED)
POSEK_QUEUE_CREATE(31, PRIORITY_31_Q_SIZE, OS_PRIORITY_31_MAX_STACK_SIZE)
#endif
